name: Build
on:
  push:
    branches:
      - dev
jobs:
  compile:
    name: Run tests and compile
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run Tests
        run: go test ./...
      - name: Compile
        run: go build -v -o ./bin/gba ./cli/main.go
      - name: Run Schedule jobs
        run: ./bin/gba -t ${{ secrets.GBA_TOKEN }}
