name: Prune
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 6'
jobs:
  compile:
    name: Compile and run prune jobs
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Compile
        run: go build -o ./bin/gba ./cli/*.go
      - name: Run Prune jobs
        run: ./bin/gba prune -t ${{ secrets.GBA_TOKEN }} --range :-7
