name: Schedule
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  compile:
    name: Compile and run schedule jobs
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Compile
        run: go build -v -o ./bin/gba ./cli/gba.go
      - name: Run Schedule jobs
        run: ./bin/gba run -s daily -t ${{ secrets.GBA_TOKEN }}
